### PR TITLE
updated “Optional methods in pure-Swift protocols”

### PR DESCRIPTION
**Pull request by riteshhgupta**
Added an alternative (swifter) technique on how to have optional methods in swift protocols rather than using @objc

### CODE REVIEW

**Comment by nikolaeu** [comment]
@riteshhgupta I think it's not a full working solution, since if you have a reference to protocol, which referenced to some implementation, and you will try to call the "optional" method, the version from protocol extension will be called, rather from class that implements protocol.

**Comment by riteshhgupta** [comment]
@nikolaeu may be i was not clear in my explanation so what is happening here is lets say you have 5 different tableView cells and all of them confirm to this Protocol. Now all the cell classes will have to implement the nonOptionalMethod but only few classes can implement the optionalMethod as its default definition is provided by the extension. So the class that implements the protocol its own version will be call always and the ones which didn't implement then the extension version will be called. Its a full working solution. I'm sharing it only after testing it. Also I have done the same in one of my recent client projects as well & its working all fine :)

**Comment by riteshhgupta** [comment]
@radex @ksm thoughts on the above conversation ?

**Comment by jklausa** [comment]
I think it's a clever hack, but I wouldn't dare to call it a 'optional methods in swift protocols'.

**Comment by riteshhgupta** [comment]
@jklausa cool.. I agree its not apple documented way of having optional protocol methods but the effect is still same without too much work :wink:

**Comment by jklausa** [comment]
As per #102, the project is no longer maintained. 

Thanks for your contributions and sorry we didn't got around to incorporating them :(

**Pull request closed without merging**
