### PR TITLE
Xcode 6.3 Beta 1 - Xcode drops Mavericks support

### PR DESCRIPTION
**Pull request by beltex**
This is more of a development change than a Swift specific thing, but since you essentially have to work through Xcode, I thought it was relevant. Feel free to close if not! :)

### CODE REVIEW

**Comment by radex** [comment]
Opinion, @jklausa @ksm?

**Comment by beltex** [comment]
@jklausa @ksm Ping! :)

**Comment by jklausa** [comment]
I'll merge it if you rebase it :)

**Comment by beltex** [comment]
Done! :)

**Comment by jklausa** [comment]
Thanks for your contributions!

**Comment by beltex** [comment]
np, happy to help! :)

**Pull request merged**
